apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 312348791909.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 312348791909.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 1987a76c
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
